version: '3.3'

services:
  my_backend:
    image: asia.gcr.io/graphite-guard-341008/my_backend:2.5
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/my_backend/src
    # env_file:
    #   - ./.env.prod
    ports:
      - 3000:3000

  # my_database:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'myproject'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
# docker-compose -f docker-compose.prod.yaml build
