version: '3.3'

services:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./index.js:/myfolder/index.js
  
  # my_crawl:
  #   build:
  #     context: ../webcrawler/.
  #     dockerfile: Dockerfile.crawler
  #   ports:
  #     - 3010:3010

  my_database:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
      
