version: "3.3"

services: 
    myfolder:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/myfolder/.
        ports:
            - 3000:3000
    
    my_database:
        image: mongo:latest
        ports: 
            - 27017:27017 